version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
    ignore:
      dependency-name: "*"
      update-types: ["version-update:semver-patch"]
